#!/usr/bin/env perl


my @abbr = qw(Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec);

my @day = qw(Sun Mon Tues Wed Thurs Fri Sat);

my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);

$year += 1900;

my $month = $abbr[$mon];

my $day_of_week = $day[$wday];


#my $now = sprintf("%s %s %d %d:%d:%d %d;\n", $day_of_week, $month, $mday, $hour, $min, $sec, $year);

my $git_sha = `git rev-parse --short HEAD`;

chomp($git_sha);

open $HEADER, ">", "/home/john/git/arduino_winder/Winder/version.h" or die "Unable to create header file $?";

print $HEADER "#ifndef VERSION_H\n#define VERSION_H\n";

print $HEADER "const char git_sha[] = \"$git_sha\"\;\n";

printf $HEADER  "const char build_date[] = \"%s %s %d %d:%d:%d %d\";\n", $day_of_week, $month, $mday, $hour, $min, $sec, $year;

#print $HEADER "const char build_date[] = \"$now\"\;";

print $HEADER "#endif\n";



